

version: "3"
services:
  api:
    build: ./chat-backend
    ports:
      - "3003:3003"
    depends_on:
      - db
    container_name: blog-api
  client:
    build: ./chat-fontend
    stdin_open: true
    ports:
      - "3000:80"
    container_name: blog-client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: chat-db