

version: "3"
services:
  api:
    build: ./chat-backend
    ports:
      - "3003:3003"
    depends_on:
      - db
    container_name: blog-api

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: chat-db